server:
  port: 8093

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

#server:
#  port: 8093
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/microservices3
#    password: root
#    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect